import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Register fonts for React-PDF if needed, but for simplicity, we use standard PDF fonts here or a generic font.

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: 'Helvetica',
    color: '#0f0d0a',
    lineHeight: 1.6,
  },
  header: {
    borderBottom: '2pt solid #0f0d0a',
    paddingBottom: 10,
    marginBottom: 20,
  },
  title: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
  },
  subtitle: {
    fontSize: 10,
    color: '#7a7468',
    marginTop: 4,
  },
  body: {
    marginBottom: 10,
  },
  bold: {
    fontFamily: 'Helvetica-Bold',
  },
  amountsBox: {
    backgroundColor: '#fff8f5',
    border: '1pt solid #f5c4b3',
    borderRadius: 4,
    padding: 15,
    marginTop: 15,
    marginBottom: 15,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  amountItem: {
    width: '50%',
    marginBottom: 10,
  },
  amountLabel: {
    fontSize: 9,
    color: '#7a7468',
    textTransform: 'uppercase',
  },
  amountValue: {
    fontSize: 14,
    color: '#c8440a',
    fontFamily: 'Helvetica-Bold',
  },
  footer: {
    fontSize: 10,
    color: '#7a7468',
    marginTop: 20,
    borderTop: '1pt solid #d4cfc4',
    paddingTop: 10,
  },
});

export const NoticePDF = ({
  buyerName,
  invoiceNumber,
  invoiceDate,
  invoiceAmount,
  udyamNumber,
  daysOverdue,
  taxDisallowance,
  interestAccrued,
}: any) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Payment Notice under Section 43B(h)</Text>
          <Text style={styles.subtitle}>Income Tax Act, 1961 — MSME Development Act, 2006</Text>
        </View>

        <View style={styles.body}>
          <Text>
            To: <Text style={styles.bold}>{buyerName}</Text>
          </Text>
          <Text style={{ marginTop: 10 }}>
            This notice pertains to Invoice <Text style={styles.bold}>{invoiceNumber}</Text> dated{' '}
            <Text style={styles.bold}>{invoiceDate}</Text> for services rendered, in the amount of{' '}
            <Text style={styles.bold}>₹{invoiceAmount.toLocaleString('en-IN')}</Text>.
          </Text>
          <Text style={{ marginTop: 10 }}>
            As a registered MSME under Udyam Registration <Text style={styles.bold}>{udyamNumber}</Text>, the
            undersigned is protected under the MSMED Act, 2006. Under Section 43B(h) of the Income Tax Act, 1961, any
            unpaid MSME dues beyond 45 days become <Text style={styles.bold}>non-deductible</Text> for the payer in the
            relevant financial year.
          </Text>
        </View>

        <View style={styles.amountsBox}>
          <View style={styles.amountItem}>
            <Text style={styles.amountLabel}>Invoice amount</Text>
            <Text style={styles.amountValue}>₹{invoiceAmount.toLocaleString('en-IN')}</Text>
          </View>
          <View style={styles.amountItem}>
            <Text style={styles.amountLabel}>Days overdue</Text>
            <Text style={styles.amountValue}>{daysOverdue} days</Text>
          </View>
          <View style={styles.amountItem}>
            <Text style={styles.amountLabel}>Tax disallowance at 30%</Text>
            <Text style={styles.amountValue}>₹{Math.round(taxDisallowance).toLocaleString('en-IN')}</Text>
          </View>
          <View style={styles.amountItem}>
            <Text style={styles.amountLabel}>Interest accrued</Text>
            <Text style={styles.amountValue}>₹{Math.round(interestAccrued).toLocaleString('en-IN')}</Text>
          </View>
        </View>

        <Text style={{ fontSize: 11, marginTop: 10 }}>
          Payment is requested immediately to avoid further tax implications. This notice is generated under the
          provisions of Section 43B(h) and may be referenced in Form 3CD filing.
        </Text>

        <View style={styles.footer}>
          <Text>Generated by BillForce · Udyam verified · Legally formatted</Text>
        </View>
      </Page>
    </Document>
  );
};
